### ISSUE TITLE
Issue with registration/login

### ISSUE THREAD

**Issue by scarecr0w12** [RyanBayne/TwitchPress-Login-Extension#26]
I keep getting the following error when attempting to register via twitch

(I have most recent plugin version of main plugin, plus extensions and UM plugin)

> [19-Sep-2017 20:27:46 UTC] TwitchPress: twitchpressloginextensionlistener: Started TwitchPress Login Extension listener.
> [19-Sep-2017 20:27:46 UTC] TwitchPress: twitchpressloginextensionlistener: Listener redirecting to default login page.
> [19-Sep-2017 20:27:46 UTC] TwitchPress: twitchpressredirects: TwitchPress System Redirect Visitor To: https://www.creatorempire.org/wp-login.php?code=********&scope=channel_check_subscription+channel_commercial+channel_editor+channel_feed_edit+channel_feed_read+channel_read+channel_stream+channel_subscriptions+chat_login+collections_edit+communities_edit+communities_moderate+user_blocks_edit+user_blocks_read+user_follows_edit+user_read+user_subscriptions+viewing_activity_read&state=13143349350430&redirected-line=588&redirected-function=twitch_login_public_listener
> [19-Sep-2017 20:27:47 UTC] TwitchPress: twitchpressloginextensionlistener: Started TwitchPress Login Extension listener.
> [19-Sep-2017 20:27:47 UTC] TwitchPress: twitchpressloginextensionlistener: Listener passed and calling process_login_using_twitch().
> [19-Sep-2017 20:27:47 UTC] TwitchPress: twitchpressloginextensionlistener: Request to process login has started.
> [19-Sep-2017 20:27:47 UTC] TwitchPress: cURL_post: TwitchPress HTTPDStatus: 200
> [19-Sep-2017 20:27:47 UTC] TwitchPress: generateToken: Access token returned: ish3ikiiup8o7e0ij6cwbzgiu1s81w
> [19-Sep-2017 20:27:47 UTC] TwitchPress: cURL_get: TwitchPress HTTPDStatus: 200
> [19-Sep-2017 20:27:47 UTC] TwitchPress: checkToken: Token is valid
> [19-Sep-2017 20:27:48 UTC] TwitchPress: cURL_get: TwitchPress HTTPDStatus: 200
> [19-Sep-2017 20:27:48 UTC] PHP Fatal error:  Uncaught Error: Cannot use object of type WP_User as array in /home/creator/public_html/wp-content/plugins/twitchpress-login-extension/twitchpress-login-extension.php:748
> Stack trace:
> #0 /home/creator/public_html/wp-content/plugins/twitchpress-login-extension/twitchpress-login-extension.php(637): TwitchPress_Login->process_login_using_twitch()
> #1 /home/creator/public_html/wp-includes/class-wp-hook.php(298): TwitchPress_Login->twitch_login_public_listener('')
> #2 /home/creator/public_html/wp-includes/class-wp-hook.php(323): WP_Hook->apply_filters('', Array)
> #3 /home/creator/public_html/wp-includes/plugin.php(453): WP_Hook->do_action(Array)
> #4 /home/creator/public_html/wp-settings.php(448): do_action('init')
> #5 /home/creator/public_html/wp-config.php(89): require_once('/home/creator/p...')
> #6 /home/creator/public_html/wp-load.php(37): require_once('/home/creator/p...')
> #7 /home/creator/public_html/wp-login.php(12): require('/home/creator/p...')
> #8 {main}
>   thrown in /home/creator/public_html/wp-content/plugins/twitchpress-login-extension/twitchpress-login-extension.php on line 748
> [19-Sep-2017 20:27:48 UTC] TwitchPress: twitchpressloginextensionlistener: Started TwitchPress Login Extension listener.
> [19-Sep-2017 20:27:48 UTC] TwitchPress: twitchpressloginextensionlistener: Login listener ended on DOING_AJAX.

**Comment by scarecr0w12** [comment]
Just realized what the issue is. 

If the username of the twitch account already exists within wordpress, it throws the error above and does not register. 

@RyanBayne Any chance of adding the function to not only check if the username exists, but to tie the twitch account to a preexisting wordpress account if registration other then twitch are allowed?

**Comment by RyanBayne** [comment]
Hiya 

Replied to you in Discord just so you know. 

I don't recall covering this scenario within the plugins abilities. We need a Twitch button on the WP users account/profile page. So they can link Twitch to their account.

I know that is basic but I've been focusing on new sites right now and getting that working well. 

Did you install this on a live site or just a test site and tested very well? 👍

**Comment by RyanBayne** [comment]
Just to be clear.

The plugin pairs accounts using email address or the finding of a Twitch user ID in user meta. 

The user can change their email address to match their Twitch account one.

A quick hack for admin is entering the Twitch user ID into the user meta. 

We cannot pair accounts based on username. That would be a security issue because an existing WP user could use the name but not be the same person using that name on Twitch.

**Comment by RyanBayne** [comment]
I added a simple measure to avoid the error. 

![image](https://user-images.githubusercontent.com/25900125/30618426-4ae71784-9d92-11e7-99df-23a3c47112c4.png)

My thinking is to bring these situations to an administrators attention and manage account creation manually to ensure the Twitch user gets the best service. 

I will create a new issue for additional settings to be added to this. I will include a note for priority treatment should a partnered streamer attempt to login.

**Comment by scarecr0w12** [comment]
Yup, looks like iw as trying to register the twitch account that i used to create the app with. I think this was the issue? after taking a second look, the admin username was different then the twitch account after double checking. 

Seems that the issue is actually with using the same twitch account that the app was created with.

**Comment by RyanBayne** [comment]
The login plugin is in use and live. We're creating apps in our main Twitch accounts and login into WordPress with those main accounts. 

The account with app should not make a difference. During login your Twitch user details are queried and email address compared to WP database and then Twitch ID is queried in user meta. 

Only then will it attempt to register you. What you're saying suggests you've changed email address maybe? 

If I'm not understanding you I am sorry. About to head to bed after a troubleshooting session with Nookyyy in which we might have made good progress. So another update coming within days and if you feel there is still issues despite my update maybe I can improve things further for you too. 

Speak soon.

**Comment by scarecr0w12** [comment]
Here, i'll clarify a bit more.

When this issue popped up, i had set up the plugin with all extensions. I opened the site in a secondary browser so i could test the login function. When already logged into twitch with the User account i created the twitch Dev app i used with the plugin, it throws the listed error. When i log in with a secondary account i have, error does not get thrown and the account is created/logged in.

Side note, Email attached to the twitch account is different then the email attached to the wordpress account. 



Hopefully, that clarifies a bit more?

**Comment by RyanBayne** [comment]
This issue is resolved. 

Many changes have been done recently to make application and Twitch accounts clearer. More work is also being done right now to improve login. Update coming within days.
