### ISSUE TITLE
Fatal Error On Login With Twitch

### ISSUE THREAD

**Issue by unitedfusionentertainment** [RyanBayne/TwitchPress-Login-Extension#30]
I have just finished installing on my new hosting with Hostgator. When I try to login with my twitch account I get the following error:

Fatal error: Cannot use object of type WP_User as array in /home2/froggie/public_html/wp-content/plugins/twitchpress-login-extension/twitchpress-login-extension.php on line 813

**Comment by RyanBayne** [comment]
![image](https://user-images.githubusercontent.com/25900125/34178964-f90e36e8-e500-11e7-95e4-45daa3640775.png)

First Box: The plugin determined that your Twitch account does not match an existing account based on email address.

Second Box:  The plugin searches for an account based on Twitch user ID.

Third Box: The plugin determines that there is one existing account using the Twitch ID currently logged into Twitch.tv but if that is not true then the query is returning a response I haven't been aware of and prepared for.

**Comment by RyanBayne** [comment]
The returned value from get_users() is stdClass object! I'm totally baffled how this wasn't seen months ago. Will upload an update to the public test site then release a new version if all goes well. 

![image](https://user-images.githubusercontent.com/25900125/34179082-70e5954e-e501-11e7-9ed8-42af028d7cf8.png)

**Comment by RyanBayne** [comment]
Real cause found. 

![image](https://user-images.githubusercontent.com/25900125/34182823-be542d14-e50f-11e7-983a-a9c201a60590.png)

The plugin is creating two user meta keys for the same value which is Twitch User ID. Some parts of the plugin are searching for the wrong meta key. I think "twitchpress_id" holds the ID related to the main account and this has caused confusion. We need to seek twitchpress_twitch_id when user logs in. 

Release a new version now.

**Comment by RyanBayne** [comment]
I also want to note that the following error appears in the scenario where the WP account has a different email address from the Twitch account. The WP account has the Twitch accounts user ID in it and so the relationship exists. But the plugin goes through different steps and that led to this issue being created. 

![image](https://user-images.githubusercontent.com/25900125/34183006-81bf8910-e510-11e7-8b2e-ce0bac2166da.png)

**Comment by RyanBayne** [comment]
![image](https://user-images.githubusercontent.com/25900125/34194484-d8bd1710-e550-11e7-89a7-12d44187de29.png)
